[colors.bright]
black = "0x3B4252"
blue = "0x4f8fba"
cyan = "0x22deee"
green = "0xa8ca6f"
magenta = "0xcb68b7"
#orange = "0xde9e41"
red = "0xff6c70"
white = "0xE5E9F0"
yellow = "0xedbe5f"

[colors.normal]
black = "0x3B4252"
blue = "0x4f8fba"
cyan = "0x22deee"
green = "0xa8ca6f"
magenta = "0xcb68b7"
#orange = "0xde9e41"
red = "0xff6c70"
white = "0xE5E9F0"
yellow = "0xedbe5f"

[colors.primary]
background = "0x172038"
foreground = "0xcdd8dd"

[env]
TERM = "xterm-256color"

[font]
size = #_FONT_SIZE_#

[font.normal]
family = "#_FONT_NORMAL_FAMILY_#"
style = "#_FONT_NORMAL_STYLE_#"

[font.italic]
family = "#_FONT_ITALIC_FAMILY_#"
style = "#_FONT_NORMAL_STYLE_#"

[[keyboard.bindings]]
chars = "\u001B[28~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[29~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "ê"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "ë"
key = "K"
mods = "Alt"

[window.dimensions]
columns = 102
lines = 26

[window.padding]
x = 4
y = 4
